name: scheduler-workflow

on:
  schedule:
    - cron: '11 10 * * *'

jobs:
  daily-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: schedule-test
        run: echo "count time workflows"
      
